# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_files/ui_main_window.ui'
#
# Created: Sun Jul 22 12:02:03 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.waveform_canvas = Qt4MplCanvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveform_canvas.sizePolicy().hasHeightForWidth())
        self.waveform_canvas.setSizePolicy(sizePolicy)
        self.waveform_canvas.setMinimumSize(QtCore.QSize(600, 200))
        self.waveform_canvas.setObjectName(_fromUtf8("waveform_canvas"))
        self.verticalLayout_2.addWidget(self.waveform_canvas)
        self.mpl_canvas = Qt4MplCanvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_canvas.sizePolicy().hasHeightForWidth())
        self.mpl_canvas.setSizePolicy(sizePolicy)
        self.mpl_canvas.setMinimumSize(QtCore.QSize(400, 200))
        self.mpl_canvas.setObjectName(_fromUtf8("mpl_canvas"))
        self.verticalLayout_2.addWidget(self.mpl_canvas)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.seishub_server = QtGui.QLineEdit(self.groupBox_4)
        self.seishub_server.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.seishub_server.setObjectName(_fromUtf8("seishub_server"))
        self.gridLayout_2.addWidget(self.seishub_server, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.buffer_seconds = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.buffer_seconds.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.buffer_seconds.setSingleStep(0.5)
        self.buffer_seconds.setProperty("value", 1.0)
        self.buffer_seconds.setObjectName(_fromUtf8("buffer_seconds"))
        self.gridLayout_2.addWidget(self.buffer_seconds, 1, 1, 2, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.selected_event_id_label = QtGui.QLabel(self.groupBox_2)
        self.selected_event_id_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_event_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_event_id_label.setObjectName(_fromUtf8("selected_event_id_label"))
        self.horizontalLayout_3.addWidget(self.selected_event_id_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.selected_latitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_latitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_latitude_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_latitude_label.setObjectName(_fromUtf8("selected_latitude_label"))
        self.horizontalLayout.addWidget(self.selected_latitude_label)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.selected_longitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_longitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_longitude_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_longitude_label.setObjectName(_fromUtf8("selected_longitude_label"))
        self.horizontalLayout.addWidget(self.selected_longitude_label)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.selected_depth_label = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_depth_label.sizePolicy().hasHeightForWidth())
        self.selected_depth_label.setSizePolicy(sizePolicy)
        self.selected_depth_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_depth_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_depth_label.setObjectName(_fromUtf8("selected_depth_label"))
        self.horizontalLayout.addWidget(self.selected_depth_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.selected_origin_time_label = QtGui.QLabel(self.groupBox_2)
        self.selected_origin_time_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_origin_time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_origin_time_label.setObjectName(_fromUtf8("selected_origin_time_label"))
        self.horizontalLayout_4.addWidget(self.selected_origin_time_label)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.selected_magnitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_magnitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_magnitude_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_magnitude_label.setObjectName(_fromUtf8("selected_magnitude_label"))
        self.horizontalLayout_4.addWidget(self.selected_magnitude_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pick_table = QtGui.QTableView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pick_table.sizePolicy().hasHeightForWidth())
        self.pick_table.setSizePolicy(sizePolicy)
        self.pick_table.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.pick_table.setTabKeyNavigation(False)
        self.pick_table.setProperty("showDropIndicator", False)
        self.pick_table.setDragDropOverwriteMode(False)
        self.pick_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pick_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pick_table.setCornerButtonEnabled(False)
        self.pick_table.setObjectName(_fromUtf8("pick_table"))
        self.pick_table.horizontalHeader().setHighlightSections(False)
        self.pick_table.horizontalHeader().setSortIndicatorShown(False)
        self.pick_table.horizontalHeader().setStretchLastSection(True)
        self.pick_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.pick_table)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.load_event_button = QtGui.QPushButton(self.centralwidget)
        self.load_event_button.setObjectName(_fromUtf8("load_event_button"))
        self.gridLayout.addWidget(self.load_event_button, 3, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableView = QtGui.QTableView(self.groupBox)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_4.addWidget(self.tableView)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 3)
        self.load_missing_data = QtGui.QPushButton(self.centralwidget)
        self.load_missing_data.setObjectName(_fromUtf8("load_missing_data"))
        self.gridLayout.addWidget(self.load_missing_data, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.omega_0_label = QtGui.QLabel(self.centralwidget)
        self.omega_0_label.setObjectName(_fromUtf8("omega_0_label"))
        self.horizontalLayout_2.addWidget(self.omega_0_label)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.omega_0_var_label = QtGui.QLabel(self.centralwidget)
        self.omega_0_var_label.setObjectName(_fromUtf8("omega_0_var_label"))
        self.horizontalLayout_2.addWidget(self.omega_0_var_label)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.f_c_label = QtGui.QLabel(self.centralwidget)
        self.f_c_label.setObjectName(_fromUtf8("f_c_label"))
        self.horizontalLayout_2.addWidget(self.f_c_label)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.f_c_var_label = QtGui.QLabel(self.centralwidget)
        self.f_c_var_label.setObjectName(_fromUtf8("f_c_var_label"))
        self.horizontalLayout_2.addWidget(self.f_c_var_label)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_2.addWidget(self.label_22)
        self.Q_label = QtGui.QLabel(self.centralwidget)
        self.Q_label.setObjectName(_fromUtf8("Q_label"))
        self.horizontalLayout_2.addWidget(self.Q_label)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        self.Q_var_label = QtGui.QLabel(self.centralwidget)
        self.Q_var_label.setObjectName(_fromUtf8("Q_var_label"))
        self.horizontalLayout_2.addWidget(self.Q_var_label)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.fit_button = QtGui.QPushButton(self.centralwidget)
        self.fit_button.setObjectName(_fromUtf8("fit_button"))
        self.horizontalLayout_2.addWidget(self.fit_button)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Moment Magnitude Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "SeisHub server:", None, QtGui.QApplication.UnicodeUTF8))
        self.seishub_server.setText(QtGui.QApplication.translate("MainWindow", "http://localhost:7777", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Seconds around pick to load", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Current Event:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Event id:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_event_id_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Lat:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_latitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Lng:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_longitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_depth_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Origin Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_origin_time_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current Magnitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_magnitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Picks", None, QtGui.QApplication.UnicodeUTF8))
        self.load_event_button.setText(QtGui.QApplication.translate("MainWindow", "Load event", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Fitting", None, QtGui.QApplication.UnicodeUTF8))
        self.load_missing_data.setText(QtGui.QApplication.translate("MainWindow", "Load missing data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Ω₀=", None, QtGui.QApplication.UnicodeUTF8))
        self.omega_0_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "(σ²=", None, QtGui.QApplication.UnicodeUTF8))
        self.omega_0_var_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "f_c=", None, QtGui.QApplication.UnicodeUTF8))
        self.f_c_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "(σ²=", None, QtGui.QApplication.UnicodeUTF8))
        self.f_c_var_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Q=", None, QtGui.QApplication.UnicodeUTF8))
        self.Q_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "(σ²=", None, QtGui.QApplication.UnicodeUTF8))
        self.Q_var_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_button.setText(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Accept", None, QtGui.QApplication.UnicodeUTF8))

from qt4mplcanvas import Qt4MplCanvas
