# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_files/ui_main_window.ui'
#
# Created: Thu Aug  2 21:55:10 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.waveform_canvas = Qt4MplCanvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveform_canvas.sizePolicy().hasHeightForWidth())
        self.waveform_canvas.setSizePolicy(sizePolicy)
        self.waveform_canvas.setMinimumSize(QtCore.QSize(600, 200))
        self.waveform_canvas.setObjectName(_fromUtf8("waveform_canvas"))
        self.verticalLayout_2.addWidget(self.waveform_canvas)
        self.mpl_canvas = Qt4MplCanvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_canvas.sizePolicy().hasHeightForWidth())
        self.mpl_canvas.setSizePolicy(sizePolicy)
        self.mpl_canvas.setMinimumSize(QtCore.QSize(400, 200))
        self.mpl_canvas.setObjectName(_fromUtf8("mpl_canvas"))
        self.verticalLayout_2.addWidget(self.mpl_canvas)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.seishub_server = QtGui.QLineEdit(self.groupBox_4)
        self.seishub_server.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.seishub_server.setObjectName(_fromUtf8("seishub_server"))
        self.gridLayout_2.addWidget(self.seishub_server, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.buffer_seconds = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.buffer_seconds.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.buffer_seconds.setSingleStep(0.5)
        self.buffer_seconds.setProperty("value", 1.0)
        self.buffer_seconds.setObjectName(_fromUtf8("buffer_seconds"))
        self.gridLayout_2.addWidget(self.buffer_seconds, 1, 1, 2, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.selected_event_id_label = QtGui.QLabel(self.groupBox_2)
        self.selected_event_id_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_event_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_event_id_label.setObjectName(_fromUtf8("selected_event_id_label"))
        self.horizontalLayout_3.addWidget(self.selected_event_id_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.selected_latitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_latitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_latitude_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_latitude_label.setObjectName(_fromUtf8("selected_latitude_label"))
        self.horizontalLayout.addWidget(self.selected_latitude_label)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.selected_longitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_longitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_longitude_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_longitude_label.setObjectName(_fromUtf8("selected_longitude_label"))
        self.horizontalLayout.addWidget(self.selected_longitude_label)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.selected_depth_label = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_depth_label.sizePolicy().hasHeightForWidth())
        self.selected_depth_label.setSizePolicy(sizePolicy)
        self.selected_depth_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_depth_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_depth_label.setObjectName(_fromUtf8("selected_depth_label"))
        self.horizontalLayout.addWidget(self.selected_depth_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.selected_origin_time_label = QtGui.QLabel(self.groupBox_2)
        self.selected_origin_time_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_origin_time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selected_origin_time_label.setObjectName(_fromUtf8("selected_origin_time_label"))
        self.horizontalLayout_4.addWidget(self.selected_origin_time_label)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.selected_magnitude_label = QtGui.QLabel(self.groupBox_2)
        self.selected_magnitude_label.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.selected_magnitude_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_magnitude_label.setObjectName(_fromUtf8("selected_magnitude_label"))
        self.horizontalLayout_4.addWidget(self.selected_magnitude_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pick_table = QtGui.QTableView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pick_table.sizePolicy().hasHeightForWidth())
        self.pick_table.setSizePolicy(sizePolicy)
        self.pick_table.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.pick_table.setTabKeyNavigation(False)
        self.pick_table.setProperty("showDropIndicator", False)
        self.pick_table.setDragDropOverwriteMode(False)
        self.pick_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pick_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pick_table.setCornerButtonEnabled(False)
        self.pick_table.setObjectName(_fromUtf8("pick_table"))
        self.pick_table.horizontalHeader().setHighlightSections(False)
        self.pick_table.horizontalHeader().setSortIndicatorShown(False)
        self.pick_table.horizontalHeader().setStretchLastSection(True)
        self.pick_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.pick_table)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.load_missing_data = QtGui.QPushButton(self.centralwidget)
        self.load_missing_data.setObjectName(_fromUtf8("load_missing_data"))
        self.horizontalLayout_5.addWidget(self.load_missing_data)
        self.load_event_button = QtGui.QPushButton(self.centralwidget)
        self.load_event_button.setObjectName(_fromUtf8("load_event_button"))
        self.horizontalLayout_5.addWidget(self.load_event_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setMargin(5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(-1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.density = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.density.setFont(font)
        self.density.setMaximum(9999)
        self.density.setSingleStep(100)
        self.density.setProperty("value", 2700)
        self.density.setObjectName(_fromUtf8("density"))
        self.horizontalLayout_8.addWidget(self.density)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.v_p = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.v_p.setFont(font)
        self.v_p.setMaximum(9999)
        self.v_p.setSingleStep(100)
        self.v_p.setObjectName(_fromUtf8("v_p"))
        self.horizontalLayout_7.addWidget(self.v_p)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.v_s = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.v_s.setFont(font)
        self.v_s.setMaximum(9999)
        self.v_s.setSingleStep(100)
        self.v_s.setObjectName(_fromUtf8("v_s"))
        self.horizontalLayout_6.addWidget(self.v_s)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.fit_table = QtGui.QTableView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_table.sizePolicy().hasHeightForWidth())
        self.fit_table.setSizePolicy(sizePolicy)
        self.fit_table.setStyleSheet(_fromUtf8("font: 10pt \"Lucida Grande\";"))
        self.fit_table.setObjectName(_fromUtf8("fit_table"))
        self.verticalLayout_6.addWidget(self.fit_table)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.mean_parameter_line_1 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mean_parameter_line_1.sizePolicy().hasHeightForWidth())
        self.mean_parameter_line_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mean_parameter_line_1.setFont(font)
        self.mean_parameter_line_1.setObjectName(_fromUtf8("mean_parameter_line_1"))
        self.verticalLayout_4.addWidget(self.mean_parameter_line_1)
        self.mean_parameter_line_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mean_parameter_line_2.sizePolicy().hasHeightForWidth())
        self.mean_parameter_line_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mean_parameter_line_2.setFont(font)
        self.mean_parameter_line_2.setObjectName(_fromUtf8("mean_parameter_line_2"))
        self.verticalLayout_4.addWidget(self.mean_parameter_line_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.save_file_button = QtGui.QPushButton(self.groupBox)
        self.save_file_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file_button.sizePolicy().hasHeightForWidth())
        self.save_file_button.setSizePolicy(sizePolicy)
        self.save_file_button.setObjectName(_fromUtf8("save_file_button"))
        self.horizontalLayout_10.addWidget(self.save_file_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(-1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.omega_0_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.omega_0_label.setFont(font)
        self.omega_0_label.setObjectName(_fromUtf8("omega_0_label"))
        self.horizontalLayout_2.addWidget(self.omega_0_label)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.omega_0_var_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.omega_0_var_label.setFont(font)
        self.omega_0_var_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.omega_0_var_label.setObjectName(_fromUtf8("omega_0_var_label"))
        self.horizontalLayout_2.addWidget(self.omega_0_var_label)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.corner_frequency_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.corner_frequency_label.setFont(font)
        self.corner_frequency_label.setObjectName(_fromUtf8("corner_frequency_label"))
        self.horizontalLayout_2.addWidget(self.corner_frequency_label)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.corner_frequency_var_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.corner_frequency_var_label.setFont(font)
        self.corner_frequency_var_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.corner_frequency_var_label.setObjectName(_fromUtf8("corner_frequency_var_label"))
        self.horizontalLayout_2.addWidget(self.corner_frequency_var_label)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_2.addWidget(self.label_22)
        self.quality_factor_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quality_factor_label.setFont(font)
        self.quality_factor_label.setObjectName(_fromUtf8("quality_factor_label"))
        self.horizontalLayout_2.addWidget(self.quality_factor_label)
        self.fit_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fit_button.setFont(font)
        self.fit_button.setObjectName(_fromUtf8("fit_button"))
        self.horizontalLayout_2.addWidget(self.fit_button)
        self.accept_values_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accept_values_button.setFont(font)
        self.accept_values_button.setObjectName(_fromUtf8("accept_values_button"))
        self.horizontalLayout_2.addWidget(self.accept_values_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Moment Magnitude Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "SeisHub server:", None, QtGui.QApplication.UnicodeUTF8))
        self.seishub_server.setText(QtGui.QApplication.translate("MainWindow", "http://teide:8080", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Seconds around pick to load", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Current Event:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Event id:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_event_id_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Lat:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_latitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Lng:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_longitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_depth_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Origin Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_origin_time_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current Magnitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_magnitude_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Picks - doubleclick to choose one", None, QtGui.QApplication.UnicodeUTF8))
        self.load_missing_data.setText(QtGui.QApplication.translate("MainWindow", "Load missing data", None, QtGui.QApplication.UnicodeUTF8))
        self.load_event_button.setText(QtGui.QApplication.translate("MainWindow", "Load event", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "𝜌 [kg/m³]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "v_p [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "v_s [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Mean parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.mean_parameter_line_1.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.mean_parameter_line_2.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.save_file_button.setText(QtGui.QApplication.translate("MainWindow", "Write QuakeML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Ω₀=", None, QtGui.QApplication.UnicodeUTF8))
        self.omega_0_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "(σ²=", None, QtGui.QApplication.UnicodeUTF8))
        self.omega_0_var_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "f_c=", None, QtGui.QApplication.UnicodeUTF8))
        self.corner_frequency_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "(σ²=", None, QtGui.QApplication.UnicodeUTF8))
        self.corner_frequency_var_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Q=", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_factor_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_button.setText(QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.accept_values_button.setText(QtGui.QApplication.translate("MainWindow", "Accept", None, QtGui.QApplication.UnicodeUTF8))

from qt4mplcanvas import Qt4MplCanvas
